# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b9850b1e8071b80fe82eae87047b30c46dbcf65e76a1b19faebfbd8bd3868387c56711d602c82ed7c2aeaf95a6c17e88b25f9dbff33db65df0889addc6dfe4c1

test:
  secret_key_base: b342faa2f0623845d0855d43e6b9e1d4e026e542d19ccc12c6990342eb2cad517b004108a376562d40c9b693a1800119e0c3de149529a570b90dbe3e4f5951ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
